### ISSUE TITLE
testcc test.c file missing

### ISSUE THREAD

**Issue by neoscopio** [tschiemer/ocac#1]
Just tried to compile, but:

```
CMake Error at CMakeLists.txt:178 (add_executable):
[cmake]   Cannot find source file:
[cmake] 
[cmake]     test.c
[cmake] 
[cmake]   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
[cmake]   .hpp .hxx .in .txx
```

**Comment by tschiemer** [comment]
Hi!

I figure that's just a local test file, you can comment out the last executable in `CMakeLists.txt`.

But generally, this framework is not in a state ready to be used in the first place and requires still quite some work amongst which some refactoring, bugfixes etc.
Priority is the AES67 framework which I hope to get to work on again later this summer - in part to have an actual implementation base or case for this AES70 framework for which the adaptation specs are not there yet.

So work is momentarily paused.

**Comment by neoscopio** [comment]
Ok, I was just trying to get a "working" skeleton of an aes70 device, even if incomplete, so I could mess with it to try and create some objects. I was hopping that was what test.c was for ... Do you think I could do this without too much trouble yet?

Anyway, you probably know this already, but it's worth mentioning that there's a working aes67 free implementation here:

https://github.com/bondagit/aes67-linux-daemon

**Comment by tschiemer** [comment]
Well, last I remember I was doing some testing using the tools here (which as you will see, are not so far developed yet): https://github.com/tschiemer/ocac/tree/master/contrib/dev

So that might be a starting point to try out things, or rather to try out method calls etc which seems to be working as intended - there's no server/networking module yet, so you can not interact using the intended AES70 communication methods and I do not recall where I left this really.

I know there are some bugs (like in the ipv6 parser) and there is no testing suite yet.
I'm not sure if the essential (manager) objects are implemented yet or are up-to-date with the newest revision and in my opinion it's not really in a state where messing around as per your idea would be meaningful, I'm afraid.

I'm a bit split between continuing this implementation and starting a new one in CPP relying on classes; the object-/class-/inheritance structure of AES70 makes the implementation in C somewhat overly verbose, although it would seem to work..


As for the aes67 linux daemon, yes I'm familiar with it thanks. Well, I previously was under the impression it was a mirror of Merging's repository which has a restrictive license of the userland butler - it seems I was mistaken. But even so, I feel a linux-based implementation is not what I am aiming for, rather a system agnostic framework that would not require an OS (ie being suitable for minimalist embedded devices) and also creating bit of a toolset around AES67 and technology to go with it - as I have the impression there are not really readily available, suitable tools for working with the tech involved.

**Comment by neoscopio** [comment]
Thanks! I will take a look, I might be able to use something.
There's a new revision for aes70 coming up soon, I'm looking forward to it specially because they specify json messages for communication. I'm not expecting any skeleton implementation, so your work will still be relevant in that case.

**Comment by arneg** [comment]
Just here to note that the upcoming AES70 version (coming out this year) will most probably not contain the JSON serialization.

**Comment by neoscopio** [comment]
> 

That's a pity. I was looking forward to that. Do you have any knowledge if it would be released any generic library with the new version? Thanks

**Comment by arneg** [comment]
We will release an update to our libraries for the new version once the spec has stabilized. This includes the openly available JavaScript library https://github.com/DeutscheSoft/AES70.js . There is also https://github.com/OCAAlliance/OcaToolsAndDemos which includes a partial implementation for certain embedded devices, however I am not sure when that would be updated to support all new features.
